### ISSUE TITLE
Support replica domain controller installation

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#21]
As a metabox user, I want to be able to deploy an environment with DC in HA topology,  with primary and replica DCs. A follow up on "Other images/boxes for metabox #7"

This should be an easy win. The following things are required to be done:

PowerShell DSC, similar to this:
> https://github.com/PowerShell/xActiveDirectory
```ps
xADDomainController SecondDC
        {
            DomainName = $Node.DomainName
            DomainAdministratorCredential = $domainCred
            SafemodeAdministratorPassword = $safemodeAdministratorCred
            DnsDelegationCredential = $DNSDelegationCred
            DependsOn = "[xWaitForADDomain]DscForestWait"
        }
```

Additional option in `metabox::vagrant::dc12` vagrant handler, such as `type` which would indicate primary DC deployment by default and `replica` for replica DC. Here is how it looks with all magic hidden by metabox:

```yaml
# primary DC
- Type: "metabox::vagrant::dc12"
              Name: "DC configuration"
              Tags: [ "dc" ]
              Properties:
                execute_tests: true
              
                dc_domain_name: "Fn::GetParameter dc_domain_name"
                dc_domain_admin_name: "Fn::GetParameter dc_domain_admin_name"
                dc_domain_admin_password: "Fn::GetParameter dc_domain_admin_password"

# replica DC
- Type: "metabox::vagrant::dc12"
              Name: "DC configuration"
              Tags: [ "dc" ]
              Properties:
                execute_tests: true
                type: "replica"
              
                dc_domain_name: "Fn::GetParameter dc_domain_name"
                dc_domain_admin_name: "Fn::GetParameter dc_domain_admin_name"
                dc_domain_admin_password: "Fn::GetParameter dc_domain_admin_password"
```
