### ISSUE TITLE
VisualStudio install should detect .exe automatically

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#29]
As a metabox user, I don't want to worry about which particular names of VS installation files. 

Currently, depending on the VS edition, various setup files should be specified:
* vs_enterprise.exe
* vs_professional.exe

That complicated YAML with unnecessary details. We should rather provide VS install folder path, and then PS/DSC should figure out the rest looking for the right exe file.

Here is how it use to be:
```YAML
 - Type: "metabox::vagrant::visual_studio13"
              Name: "vs15 install"
              Tags: [ "vs_install" ]
              Properties:
                vs_domain_user_name: "soe-win2012-r2\\vagrant"
                vs_domain_user_password: "vagrant"
                vs_executable_path: "c:\\_metabox_resources\\vs2015.3_ent_enu\\vs_enterprise.exe"
                vs_product_name: "Microsoft Visual Studio Enterprise 2015 with Update 3"
                
                # VS15 woudn't give desired state over DSC check
                # TODO to troubleshoot
                #dsc_check: "1"
                execute_tests: true
                
                vs_test_product_name: "Microsoft Visual Studio Enterprise 2015 with Updates"
                vs_test_officetools_package_name: "Microsoft Office Developer Tools for Visual Studio 2015"

```

Here is how `vs_executable_path` should look like, a folder path instead of full path to exe:

```yaml
vs_executable_path: "c:\\_metabox_resources\\vs2015.3_ent_enu\\" 
```
