### ISSUE TITLE
Introduce "DependsOn" options for resources

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#30]
As a metabox user, I want to define a relationship between resources so that resources would be built in the right sequence.

Here are a few examples:
* packer build requires file resources
* Vagrant VM requires file resources 
* Vagrant VM depends on other VM to be up (SP -> SQL -> DC)

The very idea is that we should be able to reflect such relationships in YAML so that metabox would execute them in the correct order. That would simplify multi-VM environment management via CLI, vagrant/packer build would become much easier to run with dependencies on file resources (metabox would ensure files are present before running image/VM builds).

Here is an example of how it would work:
```yaml
Metabox:
    contoso-win2012:
      Type: "vagrant::stack"
            Resources:
                 dc:
                    # vm definition here
                 sql:
                    DependsOn: [ "dc" ]
                    # vm definition here
                 sp:
                    DependsOn: [ "dc", "sql" ]
                    # vm definition here
```

In such scenarios, bringing up SharePoint VM would automatically execute the same command on dc -> SQL VMs first. Similar to file resources, they would be executed before Packer/Vagrant builds.

Another example:
```yaml
file_resource1: 
   download_sharepoint

 file_resource2: 
   download_patch

vagrant_dc:

vagrant_sql:
  DependsOn: [ "file_resource1" , "file_resource2", "vagrant_dc" ]

vagrant_sp:
  DependsOn: [ "file_resource1" , "file_resource2", "vagrant_dc", "vagrant_sql" ]
```

This is an extremely useful feature to avoid frustration over missing files and VMs which weren't up.
