### ISSUE TITLE
Abstract relative "script" paths in Packer/Vagrant documents

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/metabox#33]
Metabox documents should not care nor depend on hardcoded script paths. All Packer/Vagrant scripts in the documents should not have hardcoded paths.

All scripts are delivered by metabox in a special folder, and you should never be caring for this. Instead, you should use a token, such as "${ENV:METABOX_SCRIPTS}" or ""${ENV:DOCUMENT_SCRIPTS}"."

Such move helps to abstract metabox documents from knowing where scripts are. This is important for isolation: metabox will be creating a temporary folder for every build to improve isolation and make sure parallel builds don't clash with each other. Currently, concurrent builds could impact each other as they share the same "scripts" folder - we can't delete old content, only add on top.

The only special case is Jenkins2 pipeline helper. For this one, we need to come up with long-living script folders as this groovy helper will be included on the fly within Jwnkins2 slave. Folder or script must be static and be there all the time.

Also, we should continue for a while with old "scripts" folder generation to ensure that previous builds/documents can be run, backward compatibility. In a few releases from now, this folder should be removed and all scripts should be referred via metabox variable.

Here is how it works currently, notice relative path "./scripts/packer/metabox"
```yaml
- Type: "metabox::vagrant::shell"
              Tags: [ "sql_bin" ]
              Properties:
                path: "./scripts/packer/metabox.packer.core/_metabox_dist_helper.ps1"
                env: 
                  - "METABOX_RESOURCE_NAME=sql2014sp1"
```

A better way, metabox-managed path for scripts.

```yaml
- Type: "metabox::vagrant::shell"
              Tags: [ "sql_bin" ]
              Properties:
                path: "${ENV:METABOX_SCRIPTS}/metabox.packer.core/_metabox_dist_helper.ps1"
                env: 
                  - "METABOX_RESOURCE_NAME=sql2014sp1"
```
