### ISSUE TITLE
Machine roles

### ISSUE THREAD

**Issue by shurick81** [SubPointSolutions/metabox#38]
As a SharePoint developer I need to have simplified configuration. Currently MB configuration describes provisioning of each machine separately. For example, in `contoso-win2012r2.metabox.yaml` we specify provisioning via `VagrantTemplate` for each machine. Instead, it could be great to introduce additional level of abstraction via machine roles. For example:
```yaml

# define DC 'role'
Roles:
    dc-role:
        VagrantTemplate:
            - Type: "vagrant::config::vm"
              Properties:
                box: "Fn::GetParameter soe_box_name"

            - Type: "vagrant::config::vm::provider::virtualbox"
              Properties:
                cpus: 2
                memory: 512
                machinefolder: "Fn::GetParameter custom_machine_folder"

            - Type: "metabox::vagrant::host"
              Properties:
                hostname: "Fn::GetHostName"

            - Type: "metabox::vagrant::win12soe"
              Name: "SOE configiration"
              Tags: [ "soe" ]
              Properties:

                execute_tests: false
        
            - Type: "metabox::vagrant::dc12"
              Name: "DC configuration"
              Tags: [ "dc" ]
              Properties:
                execute_tests: true
              
                dc_domain_name: "Fn::GetParameter dc_domain_name"
                dc_domain_admin_name: "Fn::GetParameter dc_domain_admin_name"
                dc_domain_admin_password: "Fn::GetParameter dc_domain_admin_password"

# then define VMs 'applying' roles
Resources:
    contoso-win2016:
      Type: "vagrant::stack"
       Resources:
           dc-primary:
                Roles: [ "dc-role" ]
           dc-replica:
                Roles: [ "dc-replica" ]
           sql:
                Roles: [ "sql14" ]
           sql-replica:
                Roles: [ "sql14-ag" ]
           sp-wfe1:
                Roles: [ "sp13-wfe" ]
           sp-wfe2:
                Roles: [ "sp13-wfe" ]
```
